This class can be used to generate a PDF document from the results of MySQL database queries.

The class can execute one or more given queries and generate dump the results as HTML tables to a temporary page file.

The PDF document is generated by calling a remote Web service that fetches the generated HTML page and convert it to the PDF format.
